# =============================================================================
# CASO 1: Imagen YA TIENE Jupyter (ej: jupyter/base-notebook)
# =============================================================================
apiVersion: v1
kind: Pod
metadata:
  name: jupyter-native-pod
  labels:
    app: jupyter-native
    user: test-user
spec:
  restartPolicy: Never
  containers:
  - name: jupyter-native
    image: jupyter/base-notebook:latest
    ports:
    - containerPort: 8888
      name: jupyter
    - containerPort: 8080
      name: custom-app
    volumeMounts:
    - name: workspace
      mountPath: /workspace
    # Jupyter ya está instalado, solo configurar
    command: ["/bin/bash", "-c"]
    args:
    - |
      # Configurar Jupyter para usar el PVC
      mkdir -p /workspace/notebooks
      cd /workspace
      
      # Iniciar Jupyter sin token (para capturar token después)
      jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root &
      
      # Simular aplicación adicional en puerto 8080
      python3 -m http.server 8080 &
      
      # Mantener contenedor vivo
      wait
  volumes:
  - name: workspace
    persistentVolumeClaim:
      claimName: jupyter-native-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jupyter-native-pvc
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: standard
  resources:
    requests:
      storage: 20Gi